// <auto-generated />
namespace DBLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _1241234 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1241234));
        
        string IMigrationMetadata.Id
        {
            get { return "201602150744377_1241234"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
